plugins {
    id "net.fabricmc.fabric-loom" version '1.15-SNAPSHOT'
    id "fr.brouillard.oss.gradle.jgitver" version "0.9.1"
    id 'com.gradleup.shadow' version '9.3.1'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }
    maven {
        name = "Forge"
        url = "https://maven.minecraftforge.net/"
    }
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "lighterend" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }

}

fabricApi {
    configureDataGeneration {
        client = true
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:$project.loader_version"

    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"


    compileOnly("com.terraformersmc:modmenu:${project.modmenu_version}")
    runtimeOnly("com.terraformersmc:modmenu:${project.modmenu_version}")
    runtimeOnly("maven.modrinth:jade:${project.jade_version}")
    compileOnly("com.github.glitchfiend:TerraBlender-fabric:${project.terrablender_version}")
    // Only comment in the line below when you're explicitly testing TerraBlender compat
//    runtimeOnly("com.github.glitchfiend:TerraBlender-fabric:${project.terrablender_version}")


    compileOnly "org.yaml:snakeyaml:2.2"
    shadow(implementation("org.yaml:snakeyaml:2.2"))

}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
    // exclude means "keep original" (assets takes priority over generated assets)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25

}

shadowJar {
    from sourceSets.main.output
    from sourceSets.client.output

    configurations = [project.configurations.shadow]
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
    from("LICENSE.BE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
    relocate "org.yaml", "${project.maven_group}.shadow.org.yaml"
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
    from("LICENSE.BE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}

sourcesJar {
    // exclude means "keep original" (assets takes priority over generated assets)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}


jgitver {
    useDirty = true
    useGitCommitID = true
    gitCommitIDLength = 8
}
