org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# Fabric Properties
minecraft_version=1.21.9
yarn_mappings=1.21.9+build.1
loader_version=0.17.2
# Mod Properties
mod_version=handled.by.jgitver
maven_group=io.github.openbagtwo.lighterend
archives_base_name=lighterend
# Dependencies
fabric_version=0.133.14+1.21.9
modmenu_version=15.0.0
