org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false
# Fabric Properties
minecraft_version=26.1-rc-2
loader_version=0.18.4
# Mod Properties
mod_version=handled.by.jgitver
maven_group=io.github.openbagtwo.lighterend
archives_base_name=lighterend
# Dependencies
fabric_version=0.144.0+26.1
# Optional
modmenu_version=18.0.0-alpha.6
jade_version=26.0.3+fabric
terrablender_version=1.21.10-21.10.0.0
