org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# Fabric Properties
minecraft_version=25w21a
yarn_mappings=25w21a+build.2
loader_version=0.16.14
# Mod Properties
mod_version=handled.by.jgitver
maven_group=io.github.openbagtwo.lighterend
archives_base_name=lighterend
# Dependencies
fabric_version=0.124.4+1.21.6
