package io.github.openbagtwo.lighterend.datagen;

import io.github.openbagtwo.lighterend.registries.LighterEndBlocks;
import io.github.openbagtwo.lighterend.registries.LighterEndBlocks.Material;
import io.github.openbagtwo.lighterend.registries.LighterEndBlocks.Wood;
import io.github.openbagtwo.lighterend.registries.LighterEndItems;
import java.util.Arrays;
import net.fabricmc.fabric.api.client.datagen.v1.provider.FabricModelProvider;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.minecraft.client.data.BlockStateModelGenerator;
import net.minecraft.client.data.BlockStateModelGenerator.BlockTexturePool;
import net.minecraft.client.data.BlockStateModelGenerator.CrossType;
import net.minecraft.client.data.ItemModelGenerator;
import net.minecraft.client.data.Models;
import net.minecraft.client.data.TexturedModel;

public class ModelProvider extends FabricModelProvider {

  protected ModelProvider(FabricDataOutput output) {
    super(output);
  }

  @Override
  public void generateBlockStateModels(BlockStateModelGenerator blockModelGenerator) {
    blockModelGenerator.registerSimpleCubeAll(LighterEndBlocks.ENDER_BLOCK);
    generateMaterialModels(blockModelGenerator, LighterEndBlocks.VIOLECITE);
    blockModelGenerator.registerSimpleCubeAll(LighterEndBlocks.MISSING_TILE);
    for (Material jadestone : Arrays.asList(
        LighterEndBlocks.AZURE_JADESTONE,
        LighterEndBlocks.SANDY_JADESTONE,
        LighterEndBlocks.VIRID_JADESTONE
    )) {
      generateMaterialModels(blockModelGenerator, jadestone);
    }

//    blockModelGenerator.registerAxisRotated(
//        LighterEndBlocks.DRAGON_BONE_BLOCK, TexturedModel.CUBE_COLUMN
//    );

    /* Note: the below creates an (incorrect) model for the base dragon block. But because
             the (correct) model generated by the above commented-out code section is included
             in the non-generated assets folder, this one gets ignored. */
    BlockTexturePool texturePool = blockModelGenerator.registerCubeAllModelTexturePool(
        LighterEndBlocks.DRAGON_BONE_BLOCK
    );
    texturePool.stairs(LighterEndBlocks.DRAGON_BONE_STAIRS);
    texturePool.slab(LighterEndBlocks.DRAGON_BONE_SLAB);

    generateMaterialModels(blockModelGenerator, LighterEndBlocks.UMBRALITH);

    blockModelGenerator.registerTintableCrossBlockState(
        LighterEndBlocks.TENANEA_SAPLING,
        CrossType.NOT_TINTED
    );
    generateWoodModels(blockModelGenerator, LighterEndBlocks.TENANEA);
  }

  public static void generateMaterialModels(BlockStateModelGenerator blockModelGenerator,
      Material material) {
    blockModelGenerator.registerCubeAllModelTexturePool(
            material.baseBlock).stairs(material.baseStairs).slab(material.baseSlab)
        .wall(material.baseWall);

    blockModelGenerator.registerCubeAllModelTexturePool(material.bricks)
        .stairs(material.brickStairs).slab(material.brickSlab).wall(material.brickWall);

    blockModelGenerator.registerCubeAllModelTexturePool(material.polished)
        .stairs(material.polishedStairs).slab(material.polishedSlab).wall(material.polishedWall)
        .button(material.button).pressurePlate(material.pressurePlate);

    blockModelGenerator.registerCubeAllModelTexturePool(material.tiles).stairs(material.tileStairs)
        .slab(material.tileSlab).wall(material.tileWall);

    blockModelGenerator.registerAxisRotated(material.pillar, TexturedModel.CUBE_COLUMN);
  }

  public static void generateWoodModels(BlockStateModelGenerator blockModelGenerator,
      Wood wood) {
    blockModelGenerator.createLogTexturePool(wood.log).log(wood.log).wood(wood.wood);
    blockModelGenerator.createLogTexturePool(wood.strippedLog).log(wood.strippedLog)
        .wood(wood.strippedWood);
    blockModelGenerator.registerCubeAllModelTexturePool(wood.planks).stairs(wood.stairs)
        .slab(wood.slab).fence(wood.fence).fenceGate(wood.gate).button(wood.button)
        .pressurePlate(wood.pressurePlate);
    blockModelGenerator.registerDoor(wood.door);
    blockModelGenerator.registerTrapdoor(wood.trapdoor);
    blockModelGenerator.registerHangingSign(wood.strippedWood, wood.sign, wood.wallSign);
    blockModelGenerator.registerHangingSign(wood.strippedWood, wood.hangingSign,
        wood.wallHangingSign);
  }

  @Override
  public void generateItemModels(ItemModelGenerator itemModelGenerator) {
    itemModelGenerator.register(
        LighterEndItems.AURORA_CRYSTAL_SHARD, Models.GENERATED
    );
    itemModelGenerator.register(
        LighterEndItems.POPPED_LUMECORN, Models.GENERATED
    );

  }


}
