package io.github.openbagtwo.lighterend.datagen;

import io.github.openbagtwo.lighterend.misc.Wood.WoodSet;
import io.github.openbagtwo.lighterend.registries.LighterEndBlocks;
import io.github.openbagtwo.lighterend.registries.LighterEndBlocks.Material;
import io.github.openbagtwo.lighterend.registries.LighterEndEquipment;
import io.github.openbagtwo.lighterend.registries.LighterEndItems;
import io.github.openbagtwo.lighterend.registries.LighterEndMobs;
import io.github.openbagtwo.lighterend.registries.LighterEndMusicDiscs;
import io.github.openbagtwo.lighterend.registries.LighterEndTrimming;
import java.util.Arrays;
import java.util.List;
import net.fabricmc.fabric.api.client.datagen.v1.provider.FabricModelProvider;
import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.minecraft.client.color.item.Dye;
import net.minecraft.client.data.models.BlockModelGenerators;
import net.minecraft.client.data.models.BlockModelGenerators.BlockFamilyProvider;
import net.minecraft.client.data.models.BlockModelGenerators.PlantType;
import net.minecraft.client.data.models.ItemModelGenerators;
import net.minecraft.client.data.models.ItemModelGenerators.TrimMaterialData;
import net.minecraft.client.data.models.model.ItemModelUtils;
import net.minecraft.client.data.models.model.ModelLocationUtils;
import net.minecraft.client.data.models.model.ModelTemplates;
import net.minecraft.client.data.models.model.TextureMapping;
import net.minecraft.client.data.models.model.TexturedModel;
import net.minecraft.client.renderer.item.ItemModel;
import net.minecraft.client.renderer.item.ItemModel.Unbaked;
import net.minecraft.client.renderer.item.properties.select.TrimMaterialProperty;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.equipment.EquipmentAsset;
import net.minecraft.world.item.equipment.EquipmentAssets;
import net.minecraft.world.item.equipment.trim.MaterialAssetGroup;
import net.minecraft.world.level.ItemLike;

public class ModelProvider extends FabricModelProvider {

  protected ModelProvider(FabricPackOutput output) {
    super(output);
  }

  @Override
  public void generateBlockStateModels(BlockModelGenerators blockModelGenerator) {
    blockModelGenerator.createTrivialCube(LighterEndBlocks.ENDER_BLOCK);
    generateMaterialModels(blockModelGenerator, LighterEndBlocks.VIOLECITE);
    blockModelGenerator.createTrivialCube(LighterEndBlocks.MISSING_TILE);
    for (Material jadestone : Arrays.asList(
        LighterEndBlocks.AZURE_JADESTONE,
        LighterEndBlocks.SANDY_JADESTONE,
        LighterEndBlocks.VIRID_JADESTONE
    )) {
      generateMaterialModels(blockModelGenerator, jadestone);
    }

//    blockModelGenerator.registerAxisRotated(
//        LighterEndBlocks.DRAGON_BONE_BLOCK, TexturedModel.CUBE_COLUMN
//    );

    /* Note: the below creates an (incorrect) model for the base dragon block. But because
             the (correct) model generated by the above commented-out code section is included
             in the non-generated assets folder, this one gets ignored. */
    BlockFamilyProvider texturePool = blockModelGenerator.family(
        LighterEndBlocks.DRAGON_BONE_BLOCK
    );
    texturePool.stairs(LighterEndBlocks.DRAGON_BONE_STAIRS);
    texturePool.slab(LighterEndBlocks.DRAGON_BONE_SLAB);

    generateMaterialModels(blockModelGenerator, LighterEndBlocks.UMBRALITH);

    generateWoodModels(blockModelGenerator, LighterEndBlocks.TENANEA);
    blockModelGenerator.createPlant(
        LighterEndBlocks.TENANEA_SAPLING,
        LighterEndBlocks.POTTED_TENANEA_SAPLING,
        PlantType.NOT_TINTED
    );
    blockModelGenerator.createTrivialBlock(LighterEndBlocks.TENANEA_LEAVES, TexturedModel.LEAVES);

    blockModelGenerator.createTrivialCube(LighterEndBlocks.UMBRELLA_TREE_CLUSTER);
    blockModelGenerator.createTrivialCube(LighterEndBlocks.UMBRELLA_TREE_CLUSTER_EMPTY);
    blockModelGenerator.createPlant(
        LighterEndBlocks.UMBRELLA_TREE_SAPLING,
        LighterEndBlocks.POTTED_UMBRELLA_SAPLING,
        PlantType.NOT_TINTED
    );
    generateWoodModels(blockModelGenerator, LighterEndBlocks.UMBRELLA);

    generateWoodModels(blockModelGenerator, LighterEndBlocks.LOTUS);

    blockModelGenerator.createPlant(
        LighterEndBlocks.GLOWSHROOM_SAPLING,
        LighterEndBlocks.POTTED_GLOWSHROOM_SAPLING,
        PlantType.EMISSIVE_NOT_TINTED
    );
    generateWoodModels(blockModelGenerator, LighterEndBlocks.GLOWSHROOM);

    blockModelGenerator.createCrossBlock(
        LighterEndBlocks.AGAVE_SEED,
        PlantType.NOT_TINTED
    );

    blockModelGenerator.createTrivialBlock(
        LighterEndBlocks.EMERALD_ICE,
        TexturedModel.CUBE.updateTexture(TextureMapping::forceAllTranslucent)
    );
    blockModelGenerator.createTrivialBlock(
        LighterEndBlocks.FERROUS_ICE,
        TexturedModel.CUBE.updateTexture(TextureMapping::forceAllTranslucent)
    );
    blockModelGenerator.createTrivialBlock(
        LighterEndBlocks.AUROUS_ICE,
        TexturedModel.CUBE.updateTexture(TextureMapping::forceAllTranslucent)
    );

    generateMaterialModels(blockModelGenerator, LighterEndBlocks.BORNITE);

    generateWoodModels(blockModelGenerator, LighterEndBlocks.DRAGON);
    blockModelGenerator.createPlant(
        LighterEndBlocks.DRAGON_SAPLING,
        LighterEndBlocks.POTTED_DRAGON_SAPLING,
        PlantType.NOT_TINTED
    );
    blockModelGenerator.createTrivialBlock(LighterEndBlocks.DRAGON_LEAVES, TexturedModel.LEAVES);
  }

  public static void generateMaterialModels(BlockModelGenerators blockModelGenerator,
      Material material) {
    blockModelGenerator.family(
            material.baseBlock).stairs(material.baseStairs).slab(material.baseSlab)
        .wall(material.baseWall);

    blockModelGenerator.family(material.bricks)
        .stairs(material.brickStairs).slab(material.brickSlab).wall(material.brickWall);

    blockModelGenerator.family(material.polished)
        .stairs(material.polishedStairs).slab(material.polishedSlab).wall(material.polishedWall)
        .button(material.button).pressurePlate(material.pressurePlate);

    blockModelGenerator.family(material.tiles).stairs(material.tileStairs)
        .slab(material.tileSlab).wall(material.tileWall);

    blockModelGenerator.createAxisAlignedPillarBlock(material.pillar, TexturedModel.COLUMN);
  }

  public static void generateWoodModels(
      BlockModelGenerators blockModelGenerator,
      WoodSet wood
  ) {
    blockModelGenerator.woodProvider(wood.log).log(wood.log).wood(wood.wood);
    blockModelGenerator.woodProvider(wood.strippedLog).log(wood.strippedLog)
        .wood(wood.strippedWood);
    blockModelGenerator.family(wood.planks).stairs(wood.stairs)
        .slab(wood.slab).fence(wood.fence).fenceGate(wood.gate).button(wood.button)
        .pressurePlate(wood.pressurePlate);
//    blockModelGenerator.family(wood.strippedLog).sign(wood.sign).hangingSign(wood.hangingSign);
    blockModelGenerator.createDoor(wood.door);
    blockModelGenerator.createTrapdoor(wood.trapdoor);
    blockModelGenerator.createShelf(wood.shelf, wood.strippedLog);
  }

  @Override
  public void generateItemModels(ItemModelGenerators itemModelGenerator) {
    for (Item item : Arrays.asList(
        LighterEndItems.AURORA_CRYSTAL_SHARD,
        LighterEndItems.LUMECORN_EAR,
        LighterEndItems.POPPED_LUMECORN,
        LighterEndItems.SILK,
        LighterEndItems.SILK_MATRIX,
        LighterEndItems.SILK_MOTH_NEST,
        LighterEndItems.UMBRELLA_JUICE,
        LighterEndItems.END_FISH_BUCKET,
        LighterEndItems.CUBOZOA_BUCKET,
        LighterEndItems.RAW_END_FISH,
        LighterEndItems.GLOW_BARB,
        LighterEndItems.END_LILY_LEAF,
        LighterEndItems.DRIED_END_LILY_LEAF,
        LighterEndBlocks.GLOWSHROOM_FUR.asItem(),
        LighterEndBlocks.AGAVE_FUR.asItem(),
        LighterEndItems.END_CREAM,
        LighterEndItems.END_POWDER,
        LighterEndItems.CRAB_CLAW,
        LighterEndItems.CRAB_MEAT,
        LighterEndItems.CRAB_CAKE,
        LighterEndItems.TOTEM_OF_TELEPORTATION,
        LighterEndItems.CRYSTALLINE_SULPHUR,
        LighterEndItems.MATCHSTICK,
        LighterEndItems.SHADOW_BERRY_SEEDS,
        LighterEndItems.SHADOW_BERRY,
        LighterEndItems.SHADOW_BERRY_COOKED,
        LighterEndItems.SHADOW_BERRY_JAM,
        LighterEndMusicDiscs.ENDSEEKER,
        LighterEndMusicDiscs.EO_DRACONA,
        LighterEndMusicDiscs.GRASPING_AT_STARS,
        LighterEndMusicDiscs.STRANGE_AND_ALIEN,
        LighterEndBlocks.CREEPING_MOSS.asItem(),
        LighterEndBlocks.UMBRELLA_FERN.asItem(),
        LighterEndBlocks.LUMECORN_SEED.asItem(),
        LighterEndBlocks.TENANEA.ladder.asItem(),
        LighterEndBlocks.TENANEA.sign.asItem(),
        LighterEndBlocks.TENANEA.hangingSign.asItem(),
        LighterEndBlocks.TENANEA_FLOWER.asItem(),
        LighterEndBlocks.TENANEA_SAPLING.asItem(),
        LighterEndBlocks.UMBRELLA.ladder.asItem(),
        LighterEndBlocks.UMBRELLA.sign.asItem(),
        LighterEndBlocks.UMBRELLA.hangingSign.asItem(),
        LighterEndBlocks.UMBRELLA_TREE_SAPLING.asItem(),
        LighterEndBlocks.CHARNIA_CYAN.asItem(),
        LighterEndBlocks.CHARNIA_GREEN.asItem(),
        LighterEndBlocks.CHARNIA_LIGHT_BLUE.asItem(),
        LighterEndBlocks.CHARNIA_ORANGE.asItem(),
        LighterEndBlocks.CHARNIA_PURPLE.asItem(),
        LighterEndBlocks.CHARNIA_RED.asItem(),
        LighterEndBlocks.LOTUS.ladder.asItem(),
        LighterEndBlocks.LOTUS.sign.asItem(),
        LighterEndBlocks.LOTUS.hangingSign.asItem(),
        LighterEndBlocks.END_LILY_SEED.asItem(),
        LighterEndBlocks.END_LOTUS_STEM.asItem(),
        LighterEndBlocks.END_LOTUS_SEED.asItem(),
        LighterEndBlocks.GLOWSHROOM.ladder.asItem(),
        LighterEndBlocks.GLOWSHROOM.sign.asItem(),
        LighterEndBlocks.GLOWSHROOM.hangingSign.asItem(),
        LighterEndBlocks.GLOWSHROOM_HYMENOPHORE.asItem(),
        LighterEndBlocks.GLOWSHROOM_SAPLING.asItem(),
        LighterEndBlocks.AGAVE_SEED.asItem(),
        LighterEndBlocks.AGAVE_BULB.asItem(),
        LighterEndBlocks.AURANT_POLYPORE.asItem(),
        LighterEndBlocks.PURPLE_POLYPORE.asItem(),
        LighterEndBlocks.END_LEVER.asItem(),
        LighterEndBlocks.OBELISK.asItem(),
        LighterEndBlocks.GOLD_CHANDELIER.asItem(),
        LighterEndBlocks.IRON_CHANDELIER.asItem(),
        LighterEndBlocks.TUBE_WORM.asItem(),
        LighterEndBlocks.NEEDLEGRASS.asItem(),
        LighterEndBlocks.MURKWEED.asItem(),
        LighterEndBlocks.DRAGON.ladder.asItem(),
        LighterEndBlocks.DRAGON.sign.asItem(),
        LighterEndBlocks.DRAGON.hangingSign.asItem(),
        LighterEndBlocks.DRAGON_SAPLING.asItem(),
        LighterEndMobs.SILK_MOTH.spawnEgg,
        LighterEndMobs.DRAGONFLY.spawnEgg,
        LighterEndMobs.END_FISH.spawnEgg,
        LighterEndMobs.CUBOZOA.spawnEgg,
        LighterEndMobs.END_SLIME.spawnEgg,
        LighterEndMobs.MOOSHROOM.spawnEgg,
        LighterEndMobs.CHORUS_CRAB.spawnEgg
    )) {
      itemModelGenerator.generateFlatItem(item, ModelTemplates.FLAT_ITEM);
    }

    for (ItemLike chandelier : LighterEndBlocks.COPPER_CHANDELIERS.asList()) {
      itemModelGenerator.generateFlatItem(chandelier.asItem(), ModelTemplates.FLAT_ITEM);
    }

    itemModelGenerator.generateTrimmableItem(
        LighterEndEquipment.SILK_ELYTRA,
        LighterEndEquipment.SILK_MATERIAL,
        Identifier.withDefaultNamespace("trims/items/chestplate_trim"),
        true
    );

    generateVanillaArmorTrims(itemModelGenerator);
  }


  public static void generateVanillaArmorTrims(ItemModelGenerators itemModelGenerator) {

    registerArmorTrim(itemModelGenerator, Items.TURTLE_HELMET, EquipmentAssets.TURTLE_SCUTE,
        ItemModelGenerators.TRIM_PREFIX_HELMET, false);
    registerArmorTrim(itemModelGenerator, Items.LEATHER_HELMET, EquipmentAssets.LEATHER,
        ItemModelGenerators.TRIM_PREFIX_HELMET, true);
    registerArmorTrim(itemModelGenerator, Items.LEATHER_CHESTPLATE, EquipmentAssets.LEATHER,
        ItemModelGenerators.TRIM_PREFIX_CHESTPLATE, true);
    registerArmorTrim(itemModelGenerator, Items.LEATHER_LEGGINGS, EquipmentAssets.LEATHER,
        ItemModelGenerators.TRIM_PREFIX_LEGGINGS, true);
    registerArmorTrim(itemModelGenerator, Items.LEATHER_BOOTS, EquipmentAssets.LEATHER,
        ItemModelGenerators.TRIM_PREFIX_BOOTS, true);
    registerArmorTrim(itemModelGenerator, Items.COPPER_HELMET, EquipmentAssets.COPPER,
        ItemModelGenerators.TRIM_PREFIX_HELMET, false);
    registerArmorTrim(itemModelGenerator, Items.COPPER_CHESTPLATE, EquipmentAssets.COPPER,
        ItemModelGenerators.TRIM_PREFIX_CHESTPLATE, false);
    registerArmorTrim(itemModelGenerator, Items.COPPER_LEGGINGS, EquipmentAssets.COPPER,
        ItemModelGenerators.TRIM_PREFIX_LEGGINGS, false);
    registerArmorTrim(itemModelGenerator, Items.COPPER_BOOTS, EquipmentAssets.COPPER,
        ItemModelGenerators.TRIM_PREFIX_BOOTS, false);
    registerArmorTrim(itemModelGenerator, Items.CHAINMAIL_HELMET, EquipmentAssets.CHAINMAIL,
        ItemModelGenerators.TRIM_PREFIX_HELMET, false);
    registerArmorTrim(itemModelGenerator, Items.CHAINMAIL_CHESTPLATE, EquipmentAssets.CHAINMAIL,
        ItemModelGenerators.TRIM_PREFIX_CHESTPLATE, false);
    registerArmorTrim(itemModelGenerator, Items.CHAINMAIL_LEGGINGS, EquipmentAssets.CHAINMAIL,
        ItemModelGenerators.TRIM_PREFIX_LEGGINGS, false);
    registerArmorTrim(itemModelGenerator, Items.CHAINMAIL_BOOTS, EquipmentAssets.CHAINMAIL,
        ItemModelGenerators.TRIM_PREFIX_BOOTS, false);
    registerArmorTrim(itemModelGenerator, Items.IRON_HELMET, EquipmentAssets.IRON,
        ItemModelGenerators.TRIM_PREFIX_HELMET, false);
    registerArmorTrim(itemModelGenerator, Items.IRON_CHESTPLATE, EquipmentAssets.IRON,
        ItemModelGenerators.TRIM_PREFIX_CHESTPLATE, false);
    registerArmorTrim(itemModelGenerator, Items.IRON_LEGGINGS, EquipmentAssets.IRON,
        ItemModelGenerators.TRIM_PREFIX_LEGGINGS, false);
    registerArmorTrim(itemModelGenerator, Items.IRON_BOOTS, EquipmentAssets.IRON,
        ItemModelGenerators.TRIM_PREFIX_BOOTS, false);
    registerArmorTrim(itemModelGenerator, Items.DIAMOND_HELMET, EquipmentAssets.DIAMOND,
        ItemModelGenerators.TRIM_PREFIX_HELMET, false);
    registerArmorTrim(itemModelGenerator, Items.DIAMOND_CHESTPLATE, EquipmentAssets.DIAMOND,
        ItemModelGenerators.TRIM_PREFIX_CHESTPLATE, false);
    registerArmorTrim(itemModelGenerator, Items.DIAMOND_LEGGINGS, EquipmentAssets.DIAMOND,
        ItemModelGenerators.TRIM_PREFIX_LEGGINGS, false);
    registerArmorTrim(itemModelGenerator, Items.DIAMOND_BOOTS, EquipmentAssets.DIAMOND,
        ItemModelGenerators.TRIM_PREFIX_BOOTS, false);
    registerArmorTrim(itemModelGenerator, Items.GOLDEN_HELMET, EquipmentAssets.GOLD,
        ItemModelGenerators.TRIM_PREFIX_HELMET, false);
    registerArmorTrim(itemModelGenerator, Items.GOLDEN_CHESTPLATE, EquipmentAssets.GOLD,
        ItemModelGenerators.TRIM_PREFIX_CHESTPLATE, false);
    registerArmorTrim(itemModelGenerator, Items.GOLDEN_LEGGINGS, EquipmentAssets.GOLD,
        ItemModelGenerators.TRIM_PREFIX_LEGGINGS, false);
    registerArmorTrim(itemModelGenerator, Items.GOLDEN_BOOTS, EquipmentAssets.GOLD,
        ItemModelGenerators.TRIM_PREFIX_BOOTS, false);
    registerArmorTrim(itemModelGenerator, Items.NETHERITE_HELMET, EquipmentAssets.NETHERITE,
        ItemModelGenerators.TRIM_PREFIX_HELMET, false);
    registerArmorTrim(itemModelGenerator, Items.NETHERITE_CHESTPLATE, EquipmentAssets.NETHERITE,
        ItemModelGenerators.TRIM_PREFIX_CHESTPLATE, false);
    registerArmorTrim(itemModelGenerator, Items.NETHERITE_LEGGINGS, EquipmentAssets.NETHERITE,
        ItemModelGenerators.TRIM_PREFIX_LEGGINGS, false);
    registerArmorTrim(itemModelGenerator, Items.NETHERITE_BOOTS, EquipmentAssets.NETHERITE,
        ItemModelGenerators.TRIM_PREFIX_BOOTS, false);
  }

  private static void registerArmorTrim(
      ItemModelGenerators generator,
      Item armor,
      ResourceKey<EquipmentAsset> equipmentAssetId,
      Identifier slotTrimPrefix,
      boolean dyeable
  ) {

    TrimMaterialData auroraTrimmer = new ItemModelGenerators.TrimMaterialData(
        MaterialAssetGroup.create("aurora"),
        LighterEndTrimming.AURORA
    );

    Identifier modelLocation = ModelLocationUtils.getModelLocation(armor);
    var itemTexture = TextureMapping.getItemTexture(armor);
    var overlayTexture = TextureMapping.getItemTexture(armor, "_overlay");

    Identifier trimModelLocation = modelLocation.withSuffix(
        "_" + auroraTrimmer.assets().base().suffix() + "_trim");
    var trimOverlayTexture = new net.minecraft.client.resources.model.sprite.Material(
        slotTrimPrefix.withSuffix("_" + auroraTrimmer.assets().assetId(equipmentAssetId).suffix()));
    ItemModel.Unbaked trimModel;
    if (dyeable) {
      generator.generateLayeredItem(trimModelLocation, itemTexture, overlayTexture,
          trimOverlayTexture);
      trimModel = ItemModelUtils.tintedModel(trimModelLocation, new Dye(-6265536));
    } else {
      generator.generateLayeredItem(trimModelLocation, itemTexture, trimOverlayTexture);
      trimModel = ItemModelUtils.plainModel(trimModelLocation);
    }

    Unbaked untrimmedModel;
    if (dyeable) {
      ModelTemplates.TWO_LAYERED_ITEM.create(modelLocation,
          TextureMapping.layered(itemTexture, overlayTexture), generator.modelOutput);
      untrimmedModel = ItemModelUtils.tintedModel(modelLocation, new Dye(-6265536));
    } else {
      ModelTemplates.FLAT_ITEM.create(modelLocation, TextureMapping.layer0(itemTexture),
          generator.modelOutput);
      untrimmedModel = ItemModelUtils.plainModel(modelLocation);
    }

    generator.itemModelOutput.accept(armor,
        ItemModelUtils.select(new TrimMaterialProperty(), untrimmedModel,
            List.of(ItemModelUtils.when(
                auroraTrimmer.materialKey(), trimModel))));
  }
}
