package io.github.openbagtwo.lighterend.datagen;

import io.github.openbagtwo.lighterend.registries.LighterEndBlocks;
import io.github.openbagtwo.lighterend.registries.LighterEndBlocks.Material;
import io.github.openbagtwo.lighterend.registries.LighterEndBlocks.Wood;
import io.github.openbagtwo.lighterend.registries.LighterEndEquipment;
import io.github.openbagtwo.lighterend.registries.LighterEndItems;
import io.github.openbagtwo.lighterend.registries.LighterEndMobs;
import io.github.openbagtwo.lighterend.registries.LighterEndMusicDiscs;
import java.util.Arrays;
import net.fabricmc.fabric.api.client.datagen.v1.provider.FabricModelProvider;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.minecraft.client.data.BlockStateModelGenerator;
import net.minecraft.client.data.BlockStateModelGenerator.BlockTexturePool;
import net.minecraft.client.data.BlockStateModelGenerator.CrossType;
import net.minecraft.client.data.ItemModelGenerator;
import net.minecraft.client.data.Models;
import net.minecraft.client.data.TexturedModel;
import net.minecraft.item.Item;
import net.minecraft.util.Identifier;

public class ModelProvider extends FabricModelProvider {

  protected ModelProvider(FabricDataOutput output) {
    super(output);
  }

  @Override
  public void generateBlockStateModels(BlockStateModelGenerator blockModelGenerator) {
    blockModelGenerator.registerSimpleCubeAll(LighterEndBlocks.ENDER_BLOCK);
    generateMaterialModels(blockModelGenerator, LighterEndBlocks.VIOLECITE);
    blockModelGenerator.registerSimpleCubeAll(LighterEndBlocks.MISSING_TILE);
    for (Material jadestone : Arrays.asList(
        LighterEndBlocks.AZURE_JADESTONE,
        LighterEndBlocks.SANDY_JADESTONE,
        LighterEndBlocks.VIRID_JADESTONE
    )) {
      generateMaterialModels(blockModelGenerator, jadestone);
    }

//    blockModelGenerator.registerAxisRotated(
//        LighterEndBlocks.DRAGON_BONE_BLOCK, TexturedModel.CUBE_COLUMN
//    );

    /* Note: the below creates an (incorrect) model for the base dragon block. But because
             the (correct) model generated by the above commented-out code section is included
             in the non-generated assets folder, this one gets ignored. */
    BlockTexturePool texturePool = blockModelGenerator.registerCubeAllModelTexturePool(
        LighterEndBlocks.DRAGON_BONE_BLOCK
    );
    texturePool.stairs(LighterEndBlocks.DRAGON_BONE_STAIRS);
    texturePool.slab(LighterEndBlocks.DRAGON_BONE_SLAB);

    generateMaterialModels(blockModelGenerator, LighterEndBlocks.UMBRALITH);

    blockModelGenerator.registerTintableCrossBlockState(
        LighterEndBlocks.TENANEA_SAPLING,
        CrossType.NOT_TINTED
    );
    generateWoodModels(blockModelGenerator, LighterEndBlocks.TENANEA);
    blockModelGenerator.registerSingleton(LighterEndBlocks.TENANEA_LEAVES, TexturedModel.LEAVES);

    blockModelGenerator.registerSimpleCubeAll(LighterEndBlocks.UMBRELLA_TREE_CLUSTER);
    blockModelGenerator.registerSimpleCubeAll(LighterEndBlocks.UMBRELLA_TREE_CLUSTER_EMPTY);
    blockModelGenerator.registerTintableCrossBlockState(
        LighterEndBlocks.UMBRELLA_TREE_SAPLING,
        CrossType.NOT_TINTED
    );
    generateWoodModels(blockModelGenerator, LighterEndBlocks.UMBRELLA);
    generateWoodModels(blockModelGenerator, LighterEndBlocks.LOTUS);

    generateWoodModels(blockModelGenerator, LighterEndBlocks.GLOWSHROOM);

    blockModelGenerator.registerTintableCrossBlockState(
        LighterEndBlocks.GLOWSHROOM_SAPLING,
        CrossType.EMISSIVE_NOT_TINTED
    );

    blockModelGenerator.registerTintableCrossBlockState(
        LighterEndBlocks.AGAVE_SEED,
        CrossType.NOT_TINTED
    );
  }

  public static void generateMaterialModels(BlockStateModelGenerator blockModelGenerator,
      Material material) {
    blockModelGenerator.registerCubeAllModelTexturePool(
            material.baseBlock).stairs(material.baseStairs).slab(material.baseSlab)
        .wall(material.baseWall);

    blockModelGenerator.registerCubeAllModelTexturePool(material.bricks)
        .stairs(material.brickStairs).slab(material.brickSlab).wall(material.brickWall);

    blockModelGenerator.registerCubeAllModelTexturePool(material.polished)
        .stairs(material.polishedStairs).slab(material.polishedSlab).wall(material.polishedWall)
        .button(material.button).pressurePlate(material.pressurePlate);

    blockModelGenerator.registerCubeAllModelTexturePool(material.tiles).stairs(material.tileStairs)
        .slab(material.tileSlab).wall(material.tileWall);

    blockModelGenerator.registerAxisRotated(material.pillar, TexturedModel.CUBE_COLUMN);
  }

  public static void generateWoodModels(BlockStateModelGenerator blockModelGenerator,
      Wood wood) {
    blockModelGenerator.createLogTexturePool(wood.log).log(wood.log).wood(wood.wood);
    blockModelGenerator.createLogTexturePool(wood.strippedLog).log(wood.strippedLog)
        .wood(wood.strippedWood);
    blockModelGenerator.registerCubeAllModelTexturePool(wood.planks).stairs(wood.stairs)
        .slab(wood.slab).fence(wood.fence).fenceGate(wood.gate).button(wood.button)
        .pressurePlate(wood.pressurePlate);
    blockModelGenerator.registerDoor(wood.door);
    blockModelGenerator.registerTrapdoor(wood.trapdoor);
    blockModelGenerator.registerHangingSign(wood.strippedLog, wood.sign, wood.wallSign);
    blockModelGenerator.registerHangingSign(wood.strippedLog, wood.hangingSign,
        wood.wallHangingSign);
  }

  @Override
  public void generateItemModels(ItemModelGenerator itemModelGenerator) {
    for (Item item : Arrays.asList(
        LighterEndItems.AURORA_CRYSTAL_SHARD,
        LighterEndItems.LUMECORN_EAR,
        LighterEndItems.POPPED_LUMECORN,
        LighterEndItems.SILK,
        LighterEndItems.SILK_MATRIX,
        LighterEndItems.SILK_MOTH_NEST,
        LighterEndItems.UMBRELLA_JUICE,
        LighterEndItems.END_FISH_BUCKET,
        LighterEndItems.CUBOZOA_BUCKET,
        LighterEndItems.RAW_END_FISH,
        LighterEndItems.GLOW_BARB,
        LighterEndItems.END_LILY_LEAF,
        LighterEndItems.DRIED_END_LILY_LEAF,
        LighterEndItems.GLOWSHROOM_FUR,
        LighterEndItems.AGAVE_FUR,
        LighterEndItems.END_CREAM,
        LighterEndItems.END_POWDER,
        LighterEndMusicDiscs.ENDSEEKER,
        LighterEndMusicDiscs.EO_DRACONA,
        LighterEndMusicDiscs.GRASPING_AT_STARS,
        LighterEndMusicDiscs.STRANGE_AND_ALIEN,
        LighterEndBlocks.CREEPING_MOSS.asItem(),
        LighterEndBlocks.UMBRELLA_FERN.asItem(),
        LighterEndBlocks.LUMECORN_SEED.asItem(),
        LighterEndBlocks.TENANEA.ladder.asItem(),
        LighterEndBlocks.TENANEA_FLOWER.asItem(),
        LighterEndBlocks.TENANEA_SAPLING.asItem(),
        LighterEndBlocks.UMBRELLA.ladder.asItem(),
        LighterEndBlocks.UMBRELLA_TREE_SAPLING.asItem(),
        LighterEndBlocks.CHARNIA_CYAN.asItem(),
        LighterEndBlocks.CHARNIA_GREEN.asItem(),
        LighterEndBlocks.CHARNIA_LIGHT_BLUE.asItem(),
        LighterEndBlocks.CHARNIA_ORANGE.asItem(),
        LighterEndBlocks.CHARNIA_PURPLE.asItem(),
        LighterEndBlocks.CHARNIA_RED.asItem(),
        LighterEndBlocks.LOTUS.ladder.asItem(),
        LighterEndBlocks.END_LILY_SEED.asItem(),
        LighterEndBlocks.END_LOTUS_STEM.asItem(),
        LighterEndBlocks.END_LOTUS_SEED.asItem(),
        LighterEndBlocks.GLOWSHROOM.ladder.asItem(),
        LighterEndBlocks.GLOWSHROOM_HYMENOPHORE.asItem(),
        LighterEndBlocks.GLOWSHROOM_SAPLING.asItem(),
        LighterEndBlocks.AGAVE_SEED.asItem(),
        LighterEndBlocks.AGAVE_BULB.asItem(),
        LighterEndBlocks.AURANT_POLYPORE.asItem(),
        LighterEndBlocks.PURPLE_POLYPORE.asItem(),
        LighterEndMobs.SILK_MOTH.spawnEgg,
        LighterEndMobs.DRAGONFLY.spawnEgg,
        LighterEndMobs.END_FISH.spawnEgg,
        LighterEndMobs.CUBOZOA.spawnEgg,
        LighterEndMobs.END_SLIME.spawnEgg
    )) {
      itemModelGenerator.register(
          item, Models.GENERATED
      );
    }

    itemModelGenerator.registerArmor(
        LighterEndEquipment.SILK_ELYTRA,
        LighterEndEquipment.SILK_MATERIAL,
        Identifier.ofVanilla("trims/items/chestplate_trim"),
        true
    );

  }


}
